### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Lord-fancypants** [xerpi/vita-udcd-uvc#11]
my vita died using this

**Comment by RY0M43CH1Z3N** [comment]
I doubt your afirmation, send information or close the incident.

**Comment by Lord-fancypants** [comment]
Maybe i did something wrong, i dont know...... im a noob
But i had to return my vita to factory setings because it wouldnt start up anymor and jailbreake it all over again

**Comment by Lord-fancypants** [comment]
thx for response btw!
