### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by xCorra** [xerpi/vita-udcd-uvc#17]
Always getting undefined reference to ksceDisplayGetFrameBufInfoForPid error, tested on Windows 7, Windows 10, Ubuntu and Debian.

**Comment by xerpi** [comment]
Thanks for spotting it, fixed in https://github.com/xerpi/vita-udcd-uvc/commit/d3e0e3f238ba30a70d5c3cec0b59c2af36c3576f.
