### ISSUE TITLE
doesnt work on system apps

### ISSUE THREAD

**Issue by KuromeSan** [xerpi/vita-udcd-uvc#2]
NPXSXXXXX range titleids dont work. and just freeze the video on the start button covering the entire screen

**Comment by xerpi** [comment]
I know, the problem is that the Vita has two buffers/display planes and I haven't found a proper way to detect which one is the front one yet,

**Comment by KuromeSan** [comment]
could you maybe check for "NPXS" in the titleid or ?

**Comment by Rufis01** [comment]
A temporary fix could be adding a combo to re-detect the planes, perhaps.

**Comment by xerpi** [comment]
Fixed in eadc97ccf6f732e1151420dc97a1a2085a6b7488 thanks to @u3shit.
