### ISSUE TITLE
Does this plugin support the Playstation TV ?

### ISSUE THREAD

**Issue by peabreu** [xerpi/vita-udcd-uvc#23]
Hello,
I have been trying to get this plugin to work with a PSTV and I could not get it to work. Maybe the PSTV is not supported (it lacks some of the usb descriptors as it has no camera ?) ? Could you please clarify this issue ?

**Comment by xerpi** [comment]
I guess it should work if the PSTV had a slave USB port instead of the master USB port it has.

**Comment by peabreu** [comment]
Thanks for the explanation.
