### ISSUE TITLE
OSK does not show in VitaShell

### ISSUE THREAD

**Issue by 0lorak** [xerpi/vita-udcd-uvc#28]
With the 1.3 update of this plugin it is now possible to see on a monitor the Seetings, Browser amognother bubbles. We can even see the on-screen-keyboard (OSK) in those bubbles. However, when editing a plain .txt file, for example, in VitaShell this OSK does not appear. Any insight?

love this plugin btw.

**Comment by xerpi** [comment]
Check this: https://github.com/xerpi/vita-udcd-uvc/issues/2#issuecomment-449549960
Looks like OSK is on the other plane.
