### ISSUE TITLE
It's not working for me

### ISSUE THREAD

**Issue by dkrmdi** [xerpi/vita-udcd-uvc#29]
I have deleted all other plugins, but it still did not work for me.

I am on FW 3.60. I connected my vita to my Surface 3. But the Sufrace 3 only recognized my vita as MTP or type B.

Is it a working plugin? I am just really fruatrated from wasting my time trying to get this thing to work.

I wonder if it's the Surface 3 that has a problem. After all it is a low profile PC. My Surface 3 is on Windows 10.

**Comment by dkrmdi** [comment]
https://gbatemp.net/threads/mod-60-fps-psvita-usb-streaming-uvc-usb-video-class-limit-to-504p.514185/

Thos mod worked for me. But the lastest plugin did not. I wonder why.

**Comment by dkrmdi** [comment]
Version 1.3 works. The photo app did not seem to work though.

**Comment by dkrmdi** [comment]
Okay. I got the version 1.4 to work. I figured out what was the problem.

I installed it through Autoplugin and Autoplugin did not put ".skprx" in the config.txt. That threw off everything. I edited the config.txt and now it works like a charm.

Thank you very much for the great plugin.

**Comment by xerpi** [comment]
Glad to hear that it's working.
