### ISSUE TITLE
Vita not recognising as a USB video device

### ISSUE THREAD

**Issue by Moorere123** [xerpi/vita-udcd-uvc#39]
Hi all,

I set up this just like all the guides told me to but no matter what happens it doesn't seem to count as a webcam device. Sounds doesn't really like to work a lot but I can deal with that in due course.

I am a novice to this kind of thing, PS VITA 2000 is 3.65, H-Encore, VitaShell and Enso installed. Put the plugin as instructed in the ur0:tai folder but it doesn't seem to be working. Doesn't bring up anything to do with content manager so assume it is running but really I have no idea.

Any help you can supply would be great.

Thanks in advance

**Comment by xerpi** [comment]
Have you also added the plugin path to the `*KERNEL` section of taiHEN's `config.txt`?

**Comment by Moorere123** [comment]
Do you mean in the UR0 folder, tai/, config.txt? if so yes.

it reads-   ur0:tai/udcd_uvc.skprx

**Comment by xerpi** [comment]
You have to do two steps:
1. Copy the plugin
2. Tell taiHEN you want to load the plugin by editing the text file located in ur0:tai/config.txt and adding the path where you copied the plugin

**Comment by Moorere123** [comment]
So, I copied the plugin to ur0:tai and in the same folder I changed the config.txt to ur0:tai/udcd_uvc.skprx under the *Kernel section 

I've reset it again but nothing has changed. I don't think it registers as a usb camera on my computer for some reason. Am I doing something wrong?

**Comment by xerpi** [comment]
It sounds right then. You have to wait ~5sec after the Vita boots to let the plugin init.
Does the content manager assistant pop up when you plug the USB cable?

**Comment by Moorere123** [comment]
The content manager doesn't pop up. I've kept it running for quite a while but nothing changes, it never becomes a camera device.

I have bitdefender if that might be a cause. It doesn't look at webcam settings though.

**Comment by xerpi** [comment]
If you use Windows 10 you might have to change the Camera access permissions on the Privacy Settings.

Also open the USB device explorer and check if the Vita is showing there.

**Comment by Moorere123** [comment]
I should probably add that the PS Vita appears on my device manager under portable devices if that means anything.

The setting I have already changed.

Is USB Device Explorer something I need to download or should my computer already have it?

**Comment by xerpi** [comment]
I don't use windows so I don't know the exact name of the app. I mean something that lets you see your USB devices.

Like this
![image](https://user-images.githubusercontent.com/560596/65813789-dfc6a080-e1d9-11e9-9321-9b65ce1e1b78.png)

Also check this: https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/usbview

**Comment by Moorere123** [comment]
![device manger](https://user-images.githubusercontent.com/55904181/65813846-4e751f80-e215-11e9-86e5-e67d56edfd9e.png)

This is what it currently looks like.

**Comment by Moorere123** [comment]
Apologies it seems changing the location and redoing the .txt to UX0 from UR0 the matter has fixed itself. Thank you for your help :).

**Comment by xerpi** [comment]
Glad it works now.

**Comment by NormanFoxLee** [comment]
> 
> 
> Glad it works now.

I tried the same - did not help. Does it have another solution?

**Comment by NormanFoxLee** [comment]
@xerpi Now I fixed it. You need to update config that is inside ux0 disk, not ur0! There are 2 configs.

**Comment by faiznaaman** [comment]
> @xerpi Now I fixed it. You need to update config that is inside ux0 disk, not ur0! There are 2 configs.

Could you please elaborate more on this? I have problem my vita not being detected by PC (Windows 10) using USB, let alone as a camera device. No matter using vitashell or QCMA, it seem that USB connection from my vita is not being detected at all. No notification sound or whatsoever.

**Comment by xerpi** [comment]
> > @xerpi Now I fixed it. You need to update config that is inside ux0 disk, not ur0! There are 2 configs.
> 
> Could you please elaborate more on this? I have problem my vita not being detected by PC (Windows 10) using USB, let alone as a camera device. No matter whether I was using Vitashell or QCMA, it seems that the USB connection from my vita is not being detected at all. No notification sound or whatsoever. I'll try to connect to android box (using the USB Camera app) but still no luck. I've tried using 2 new cable but nothing being detected.

Does the VIta (maybe as an unknown device) appear here when you connect it?
![image](https://user-images.githubusercontent.com/560596/132180641-790dc887-0eb6-40a3-8a30-d67bd305121e.png)

**Comment by NormanFoxLee** [comment]
> > @xerpi Now I fixed it. You need to update config that is inside ux0 disk, not ur0! There are 2 configs.
> 
> Could you please elaborate more on this? I have problem my vita not being detected by PC (Windows 10) using USB, let alone as a camera device. No matter whether I was using Vitashell or QCMA, it seems that the USB connection from my vita is not being detected at all. No notification sound or whatsoever. I'll try to connect to android box (using the USB Camera app) but still no luck. I've tried using 2 new cable but nothing being detected.

Sorry, I don’t even remember how exactly it was done (it was 1+ year ago), but I followed this thread and just after doing the solution on ux0 disk it started working.

**Comment by faiznaaman** [comment]
> > > @xerpi Now I fixed it. You need to update config that is inside ux0 disk, not ur0! There are 2 configs.
> > 
> > 
> > Could you please elaborate more on this? I have problem my vita not being detected by PC (Windows 10) using USB, let alone as a camera device. No matter whether I was using Vitashell or QCMA, it seems that the USB connection from my vita is not being detected at all. No notification sound or whatsoever. I'll try to connect to android box (using the USB Camera app) but still no luck. I've tried using 2 new cable but nothing being detected.
> 
> Does the VIta (maybe as an unknown device) appear here when you connect it?
> ![image](https://user-images.githubusercontent.com/560596/132180641-790dc887-0eb6-40a3-8a30-d67bd305121e.png)

Nothing. Not even a Windows sound when detecting an USB connection. It seems like the USB data transfer has been disabled/ dead. But my Vita still can charge. My Vita is 1000 model on 3.60 Enso using SD2VITA 512GB full games with 8GB original Sony memory card, working well. I bought it second hand. I have 3 charging cables, all for test, but with no avail. They can charge but nothing on data transfer. When I plugged the cable, there wasn't a notification/ loading icon.
