### ISSUE TITLE
Cannot get the vita to be recognized by OBS/VLC/Win10 Camera app

### ISSUE THREAD

**Issue by SMNFXCN** [xerpi/vita-udcd-uvc#41]
i cannot get this to work, i have been trying for hours, and i've tried many things like reinstalling the drivers using zadig and swapping which line this uvc_udcd plugin is on. the vita does not have a pop and say "connecting...". the pc recognizes it but doesnt show it as a usb camera.

**Comment by HoneyOTU1337** [comment]
i use sd2vita, and only use ur0: to load my plugins, here is my config.txt below.
# This file is used as an alternative if ux0:tai/config.txt is not found.
# For users plugins, you must refresh taiHEN from HENkaku Settings for
# changes to take place.
# For kernel plugins, you must reboot for changes to take place.
*KERNEL
ur0:tai/gamesd.skprx
ur0:tai/ioplus.skprx
ux0:app/PSPEMUCFW/sce_module/adrenaline_kernel.skprx
ur0:tai/ds4vita.skprx
ur0:tai/nonpdrm.skprx
ur0:tai/repatch.skprx
ur0:tai/udcd_uvc.skprx
ur0:tai/videoDebug.skprx
ur0:tai/lolicon.skprx
# henkaku.skprx is hard-coded to load and is not listed here
*main
ur0:tai/download_enabler.suprx
ur0:tai/pngshot.suprx
ur0:tai/shellsecbat.suprx
ur0:tai/henkaku.suprx
# main is a special titleid for SceShell
ur0:tai/henkaku.suprx
# this is for modifying the version string
ur0:tai/henkaku.suprx
# this is for modifying the version string in settings widget
ur0:tai/henkaku.suprx
*ALL
ur0:tai/vitagrafix.suprx
*NPXS10015
ur0:tai/henkaku.suprx
ur0:tai/macspoofer.suprx
*NPXS10016
ux0:tai/henkaku.suprx
ur0:tai/macspoofer.suprx

**Comment by HoneyOTU1337** [comment]
update: i have switched pcs when i made the two posts above, and i have access to my older pc. the plugin works on the old pc. the plugin is working, but my newer pc refuses to acknowledge it as a camera, where my old pc does it just fine.

**Comment by HoneyOTU1337** [comment]
![image](https://user-images.githubusercontent.com/38541316/70367843-6f439c00-187a-11ea-919a-f533b0818ff4.png)
idk if this will help

**Comment by xerpi** [comment]
Make sure the USB webcam permissions are enabled in the Windows 10 camera settings:
![image](https://user-images.githubusercontent.com/560596/70567150-ac1ed400-1b95-11ea-8ec0-279527a1bbb9.png)

**Comment by HoneyOTU1337** [comment]
![image](https://user-images.githubusercontent.com/38541316/70662056-e04cd000-1c3b-11ea-8d79-5deba4a6277f.png)

**Comment by Drakonas** [comment]
Two things. You are using ioPlus 0.1 and not 0.2, correct? 0.2 is known to cause issues if you use iTLS or VitaGrafx. Also, why are you using gamesd instead of Storage Manager? https://github.com/CelesteBlue-dev/PSVita-StorageMgr/releases

Other than that, if it works on one PC and not the other, obviously the issue is with the new PC and not the plugin.

**Comment by Adam-848** [comment]
did anyone figure out what the exact problem was? it works on a friends laptop but not mine, i tried everything above with no luck
