### ISSUE TITLE
No PSVITA OSD events ingame

### ISSUE THREAD

**Issue by Dr4goonDemon** [xerpi/vita-udcd-uvc#42]
Hi, I'm using UDCD-UVC-LCD for my ps vita 2000 and I encountered this issue: when playing games if I unlock a Trophy it didn't show up on the pc screen and also when I try to write using my dualshock 4 it only shows the OSK on the vita but not on the PC screen This happens also with if I press the ps button longer and the system menu, or try to change volume, basically all the PSVITA osd events in game, I want to know if is an issue and if it will be addressed soon, so I can play my PS Vita like a PS VITA TV, ist annoying but not game breaking, everything else I tested works fine.

**Comment by HoneyOTU1337** [comment]
v1.3 fixed this

**Comment by Dr4goonDemon** [comment]
My PS VITA is on 3.65 enzo and I use the UDCD-UVC-LCD off 1.4 from Autoplugin and I still gettin that issue when I'm on a game, when I'm on the Home Menu I see the OSD but not on a game whether is a ps vita game or a psp game

**Comment by xerpi** [comment]
That's because the PSVita display controller has 2 overlay planes. Unfortunately, I can only send the contents of one of them to the PC (sending both would kill the performance since it would require manual compositing).
