### ISSUE TITLE
v1.5 full resolution (60FPS Not Possible) Limited by Bandwidth on PotPlayer

### ISSUE THREAD

**Issue by tabnk** [xerpi/vita-udcd-uvc#56]
As shown below

![Vita1](https://user-images.githubusercontent.com/10874582/81467712-2028db00-920d-11ea-8915-7ca4dcc45f16.png)

**Comment by Lulech23** [comment]
I can confirm this issue. Tried on a variety of PCs using both USB 2 and 3 ports. All were limited to 339250 kbps tops. This is of course on v1.5 running at 960x544.

**Comment by berserkingyadis** [comment]
Is this a plugin issue? Do you have experience with a better Player on PC that one could switch to?

**Comment by tabnk** [comment]
Vita is technically not feasible.
