### ISSUE TITLE
Black screen after warning of epilepsy

### ISSUE THREAD

**Issue by SheidCraft** [xerpi/vita-udcd-uvc#58]
I heard that a similar problem is treated by installing 10 or more seconds in the plugin file, but I don’t have a PC nearby, and I can’t do this through the phone. Can someone throw off a finished file?

**Comment by xerpi** [comment]
v1.5 with 10s delays: [udcd_uvc_1.5_10s_delay.zip](https://github.com/xerpi/vita-udcd-uvc/files/4638006/udcd_uvc_1.5_10s_delay.zip)
