### ISSUE TITLE
Instantly crashing

### ISSUE THREAD

**Issue by DavidTheTech** [xerpi/vita-udcd-uvc#62]
ps vita is the 1003 model

after i install the plugin and restart the vita it doesnt even get past the health warning screen, then it goes blank and the ps light flashes 3-5 times then turns off

**Comment by xerpi** [comment]
https://github.com/xerpi/vita-udcd-uvc/issues/58
https://github.com/xerpi/vita-udcd-uvc/issues/46

**Comment by DavidTheTech** [comment]
Thank you

**Comment by ShuFengYingt** [comment]
> #58 #46

No fix
