### ISSUE TITLE
Ps vita brick and how to fix it

### ISSUE THREAD

**Issue by ZFGFade** [xerpi/vita-udcd-uvc#63]
Straight up bricked my ps vita with both the universal and the OLED psv1000 version. Idk what causes it, I installed it with auto plugin 2, haven't tried manually but I doubt it would work. When I tried to boot the logo would disappear and the ps vita would turn off again, I fixed it by taking out my sd2vita and only having the PlayStation memory card in (not sure if this step is necessary), and used the button combo (power+ps+L+select+start), when it booted I went to vitashell, ur0:tai then deleted udcd_uvc____.skprx.

I want to get this working but idk what causes it and how to fix it. I can supply extra details if necessary. 

Any alternatives potentially? 

EDIT: Just tried to manually install didn't work

EDIT2: This delay and putting it on the last line of *KERNEL worked thank you very much

File with delay: https://github.com/xerpi/vita-udcd-uvc/issues/34#issuecomment-584118027

**Comment by xerpi** [comment]
v1.6 with 15s delay: [udcd_uvc_v1.6_15s_delay.zip](https://github.com/xerpi/vita-udcd-uvc/files/4906559/udcd_uvc_v1.6_15s_delay.zip)

**Comment by ZFGFade** [comment]
> v1.6 with 15s delay: [udcd_uvc_v1.6_15s_delay.zip](https://github.com/xerpi/vita-udcd-uvc/files/4906559/udcd_uvc_v1.6_15s_delay.zip)

Thank you very much! If there isn't a disadvantage with it being at 10 or 15 sec instead of 5 could you make all future versions include this fix?

**Comment by xerpi** [comment]
> > v1.6 with 15s delay: [udcd_uvc_v1.6_15s_delay.zip](https://github.com/xerpi/vita-udcd-uvc/files/4906559/udcd_uvc_v1.6_15s_delay.zip)
> 
> Thank you very much! If there isn't a disadvantage with it being at 10 or 15 sec instead of 5 could you make all future versions include this fix?

Yes I'll do that :)

**Comment by ZFGFade** [comment]
> > > v1.6 with 15s delay: [udcd_uvc_v1.6_15s_delay.zip](https://github.com/xerpi/vita-udcd-uvc/files/4906559/udcd_uvc_v1.6_15s_delay.zip)
> > 
> > 
> > Thank you very much! If there isn't a disadvantage with it being at 10 or 15 sec instead of 5 could you make all future versions include this fix?
> 
> Yes I'll do that :)

Thank you for the quick reply and continued development for the ps vita.
