### ISSUE TITLE
vita doesnt boot when PSVshell  is installed.

### ISSUE THREAD

**Issue by treypop** [xerpi/vita-udcd-uvc#68]
what the title says.

**Comment by xerpi** [comment]
Try putting it at the last line of *KERNEL section.

**Comment by treypop** [comment]
It's giving me the same problem. This is what my config file looks like. 
![config](https://user-images.githubusercontent.com/24729682/89577908-fd4f9800-d7f6-11ea-97ed-2f63e0e12ea2.png)

**Comment by treypop** [comment]
moving it from ur0 to ux0 and adding it to the ux0 config file fixed the boot problem

**Comment by treypop** [comment]
https://github.com/xerpi/vita-udcd-uvc/issues/34#issuecomment-657029276
That ultimately fixed my problem.
