### ISSUE TITLE
Audio Lag with 3.5 mm jack

### ISSUE THREAD

**Issue by cainkirisgai** [xerpi/vita-udcd-uvc#70]
awesome work on getting this to be able to perform so well. Im not sure if it has already been solved or there is no real way to prevent it, but i get about a half second audio delay while connecting to a 3.5mm jack and using obs. Im not sure if its me or if i need to try and hunt down a 0 delay codec for pc to minimize or eliminate the lag altogether. If any ideas please share with me if I find anything myself and it was on my end i will close this and submit my findings. Thanks again for the awesome work.

**Comment by cainkirisgai** [comment]
nm i got it ^_^ seems that trying to listen through OBS causes the lag but if i listen to it normally through windows sound it works fine with no lag at all did a test recording in obs just to be sure and all checks out.

**Comment by voild980** [comment]
just an questiono... Did you play at 1280x720? If so, can you show me your tai folder, and FW?

**Comment by cainkirisgai** [comment]
i did use 1280x720 and the firmware is 3.60 enso 
![Screenshot (6)](https://user-images.githubusercontent.com/34290512/90822175-0d409f00-e302-11ea-929d-1b0c73466c6d.png)
![Screenshot (7)](https://user-images.githubusercontent.com/34290512/90822183-0fa2f900-e302-11ea-87dd-fd89498e52ec.png)

(i think since its 2 Japanese characters)-11

**Comment by voild980** [comment]
Strange... mine only works at 960x544. 1280x720 gives me either an black screen or an error code.
