### ISSUE TITLE
Detecting the PS Vita as a Mic and playing a white screen with my rooms sounds

### ISSUE THREAD

**Issue by OmegaXavier** [xerpi/vita-udcd-uvc#82]
Hi.

To my understanding this app (awesome job, keep it up!!) should detect the psVita as soon as it is plugged in and so it does, yet, it takes it as a Mic so it can't be played on PCs screen.

this app is really promising, please don't stop :)

**Comment by Speyd3r** [comment]
How did you try to use it? With OBS? If so, are you sure you selected the Vita and not something else? Cause it sounds more like you selected some Webcam that has in integrated Mic that is maybe facing some wall or something

**Comment by OmegaXavier** [comment]
OBS?

dunno what that is.

I just installed your app, plugged the Vita through USB, then the PC itself started "installing", more like setting up the device, and then your app would detect it as a microphone showing a white screen... kinda funny if you'll ask me, just it wasn't operating as I had expected.

I even had the access to the "options" you provide but none of them would allow to bypass this situation.


Hey, you're creating a really cool solution, please keep it up.

Feel free to ask whatever else you want.

Tip: consider creating a log file system :)

**Comment by Speyd3r** [comment]
What program? This is just a plugin for the vita that you drop in the tai folder (and add to the config.txt)
There is no PC program attached to this? How did you try to view the Vitas screen?

**Comment by OmegaXavier** [comment]
ohhh oucch.. i may be confused maybe?

Allow me to confirm this and i'll either rephrase it or delete the post myself :P


Cheers

**Comment by OmegaXavier** [comment]
Yes, this was posted on the wrong place, this case was meant to be created on PSVitaPlay's Github.

My apologies
