### ISSUE TITLE
Remote Play

### ISSUE THREAD

**Issue by MatthewRyabtsun** [xerpi/vita-udcd-uvc#9]
Why, when logging in to the remote play application, it stops broadcasting to the computer?

**Comment by xerpi** [comment]
Explained here: https://github.com/xerpi/vita-udcd-uvc/issues/2#issuecomment-449549960

**Comment by KuromeSan** [comment]
Suggesting closing this since now it works in system apps due to pull request #25  https://github.com/xerpi/vita-udcd-uvc/pull/25
