### ISSUE TITLE
When trying to connect via USB Cable to PC with QCMA, says "An error occurred (C0-7926-4)"

### ISSUE THREAD

**Issue by hedhehd** [xerpi/vita-udcd-uvc#94]
When I deactivate this Plugin, It just works so I don't know what's causing this.

**Comment by Awesomeguys9000** [comment]
> When I deactivate this Plugin, It just works so I don't know what's causing this.

this plugin overrides the vita's normal USB functions, you cannot use other USB functions when using this plugin (otherwise how is it going to stream video over the very limited USB 2.0 connection????)

**Comment by hedhehd** [comment]
Forgot to close it for a whopping 2 years
