### ISSUE TITLE
Can't get video to work on MacOS (Apple M1)

### ISSUE THREAD

**Issue by yukipastelcat** [xerpi/vita-udcd-uvc#98]
Cannot get video output to work on MacOS with 2020 MacBook Pro with M1 processor, output from camera in OBS, Photo Booth and QuickTime is missing, however it works when trying to preview camera output on Windows using Parallels Desktop

**Comment by beckmx** [comment]
it does work, but with other apps, I published a video on twitter

**Comment by GrayJack** [comment]
On what apps?
